export const SIGE_ERROR_CODES = [
  "AUTH_REQUIRED",
  "FORBIDDEN",
  "NOT_FOUND",
  "INVALID_ARGUMENT",
  "IDEMPOTENCY_KEY_REQUIRED",
  "REQUEST_HASH_MISMATCH",
  "ACADEMIC_YEAR_CLOSED",
  "ACADEMIC_YEAR_NOT_OPEN",
  "ASSESSMENT_RESULTS_INCOMPLETE",
  "RESULT_IS_NOT_PUBLISHED",
  "PUBLISHED_RESULT_REQUIRES_CORRECTION",
  "PUBLISHED_RESULT_REQUIRES_CORRECTION_COMMAND",
  "CORRECTION_REASON_REQUIRED",
  "PEDAGOGICAL_PARALLELISM_NOT_CONFIGURED",
  "FINAL_EXAM_ONLY_ALLOWED_FOR_9_AND_12",
  "THREE_PUBLISHED_TRIMESTER_RESULTS_REQUIRED",
  "TRIMESTER_RESULT_INCOMPLETE",
  "FREQUENCY_RESULT_INCOMPLETE",
  "PUBLISHED_FREQUENCY_RESULT_REQUIRED",
  "PUBLISHED_EXAM_RESULT_REQUIRED",
  "EXAM_RESULT_NOT_FOUND",
  "ASSESSMENT_RESULT_IS_NOT_EXAM",
  "SCHEDULE_TEACHER_CONFLICT",
  "TEACHER_ASSIGNMENT_CONTEXT_MISMATCH",
  "COURSE_OFFERING_NOT_FOUND",
  "ASSESSMENT_PERIOD_NOT_FOUND",
  "STUDENT_NOT_COURSE_PARTICIPANT",
  "FINANCIAL_SCOPE_VIOLATION",
  "PAYMENT_ALLOCATION_EXCEEDS_PAYMENT",
  "PAYMENT_ALLOCATION_EXCEEDS_CHARGE",
  "RECEIPT_PAYMENT_NOT_CONFIRMED",
  "PAYMENT_ALREADY_REVERSED",
  "SCHOOL_NOT_FOUND",
  "STUDENT_NOT_FOUND",
  "STUDENT_SCHOOL_NUMBER_ALREADY_EXISTS",
  "NATIONAL_ID_ALREADY_EXISTS",
  "GUARDIAN_IDENTITY_NUMBER_ALREADY_EXISTS",
  "ACTIVE_ENROLLMENT_ALREADY_EXISTS",
  "ENROLLMENT_NOT_FOUND",
  "ENROLLMENT_NOT_PLACABLE",
  "CLASS_GROUP_NOT_FOUND",
  "CLASS_GROUP_NOT_OPEN",
  "CLASS_CONTEXT_MISMATCH",
  "PLACEMENT_DATE_OUTSIDE_ACADEMIC_YEAR",
  "CLASS_CAPACITY_REACHED",
  "GRADE_LEVEL_NOT_FOUND",
  "PATHWAY_NOT_FOUND",
  "CLASS_GROUP_PATHWAY_CYCLE_MISMATCH",
  "CLASS_GROUP_PATHWAY_SCHOOL_MISMATCH",
  "TEACHER_NOT_FOUND_IN_SCHOOL",
  "DIRECTOR_MUST_TEACH_CLASS",
  "DIRECTOR_DATES_OUTSIDE_ACADEMIC_YEAR",
  "COURSE_OFFERING_CLASS_CONTEXT_MISMATCH",
  "SUBJECT_NOT_FOUND",
  "COURSE_OFFERING_SUBJECT_SCHOOL_MISMATCH",
  "CURRICULUM_SUBJECT_NOT_FOUND",
  "COURSE_OFFERING_CURRICULUM_CONTEXT_MISMATCH",
  "COURSE_OFFERING_SUBJECT_MISMATCH",
  "ACADEMIC_YEAR_NOT_FOUND",
  "ACADEMIC_YEAR_EDITABLE",
  "ACADEMIC_YEAR_NOT_EDITABLE",
  "SECTION_CODE_REQUIRED",
  "INVALID_CLASS_CAPACITY",
  "CLASS_GROUP_NOT_EDITABLE",
  "CLASS_PATHWAY_CHANGE_REQUIRES_EMPTY_CLASS",
  "CLASS_CLOSE_DATE_OUTSIDE_ACADEMIC_YEAR",
  "CLASS_GROUP_ALREADY_CLOSED",
  "COURSE_OFFERING_NOT_ASSIGNABLE",
  "TEACHER_ASSIGNMENT_DATES_OUTSIDE_ACADEMIC_YEAR",
  "TEACHER_NOT_FOUND",
  "TEACHER_SCHOOL_MISMATCH",
  "TRANSFER_REASON_REQUIRED",
  "ENROLLMENT_NOT_TRANSFERABLE",
  "CURRENT_CLASS_PLACEMENT_NOT_FOUND",
  "TARGET_CLASS_NOT_FOUND",
  "TRANSFER_TARGET_CONTEXT_MISMATCH",
  "TRANSFER_TARGET_IS_CURRENT_CLASS",
  "TARGET_CLASS_NOT_OPEN",
  "TRANSFER_DATE_OUTSIDE_ACADEMIC_YEAR",
  "TRANSFER_DATE_MUST_FOLLOW_CURRENT_PLACEMENT",
  "TARGET_CLASS_CAPACITY_REACHED",
] as const;

export type SigeErrorCode = (typeof SIGE_ERROR_CODES)[number];

const KNOWN = new Set<string>(SIGE_ERROR_CODES);

export class SigeApplicationError extends Error {
  readonly code: SigeErrorCode | "UNKNOWN";
  readonly details?: unknown;
  readonly cause?: unknown;

  constructor(
    code: SigeErrorCode | "UNKNOWN",
    message: string,
    details?: unknown,
    cause?: unknown,
  ) {
    super(message);
    this.name = "SigeApplicationError";
    this.code = code;
    this.details = details;
    this.cause = cause;
  }
}

export function normalizeSigeError(error: unknown): SigeApplicationError {
  if (error instanceof SigeApplicationError) return error;

  const candidate = error as {
    message?: unknown;
    code?: unknown;
    details?: unknown;
    hint?: unknown;
  } | null;

  const message =
    typeof candidate?.message === "string" ? candidate.message : "Operação SIGE falhou.";
  const code =
    typeof candidate?.code === "string" && KNOWN.has(candidate.code)
      ? (candidate.code as SigeErrorCode)
      : KNOWN.has(message)
        ? (message as SigeErrorCode)
        : "UNKNOWN";

  return new SigeApplicationError(code, message, {
    dbCode: candidate?.code,
    details: candidate?.details,
    hint: candidate?.hint,
  }, error);
}
