import type { SigeErrorCode } from "@sige/contracts";

export function errorMessage(code: SigeErrorCode | "UNKNOWN") {
  const messages: Record<SigeErrorCode | "UNKNOWN", string> = {
    AUTH_REQUIRED: "A sua sessão terminou. Entre novamente no SIGE.",
    FORBIDDEN: "A sua conta não tem permissão para executar esta operação.",
    NOT_FOUND: "O registo solicitado não foi encontrado.",
    INVALID_ARGUMENT: "Os dados enviados não são válidos.",
    IDEMPOTENCY_KEY_REQUIRED: "Não foi possível identificar esta operação com segurança.",
    REQUEST_HASH_MISMATCH: "A operação foi enviada novamente com dados diferentes.",
    ACADEMIC_YEAR_CLOSED: "O ano letivo está fechado e não aceita esta alteração.",
    ACADEMIC_YEAR_NOT_OPEN: "O ano letivo ainda não está aberto para esta operação.",
    ASSESSMENT_RESULTS_INCOMPLETE: "Os resultados necessários ainda não estão completos.",
    RESULT_IS_NOT_PUBLISHED: "O resultado ainda não foi publicado.",
    PUBLISHED_RESULT_REQUIRES_CORRECTION: "O resultado publicado precisa de uma correção formal.",
    PUBLISHED_RESULT_REQUIRES_CORRECTION_COMMAND: "Use a operação de correção para alterar este resultado.",
    CORRECTION_REASON_REQUIRED: "Indique o motivo da correção.",
    PEDAGOGICAL_PARALLELISM_NOT_CONFIGURED: "A configuração pedagógica necessária ainda não está definida.",
    FINAL_EXAM_ONLY_ALLOWED_FOR_9_AND_12: "O exame final aplica-se apenas às classes previstas no regime em vigor.",
    THREE_PUBLISHED_TRIMESTER_RESULTS_REQUIRED: "É necessário publicar os três resultados trimestrais.",
    TRIMESTER_RESULT_INCOMPLETE: "O resultado trimestral está incompleto.",
    FREQUENCY_RESULT_INCOMPLETE: "O resultado de frequência está incompleto.",
    PUBLISHED_FREQUENCY_RESULT_REQUIRED: "É necessário publicar o resultado de frequência.",
    PUBLISHED_EXAM_RESULT_REQUIRED: "É necessário publicar o resultado do exame.",
    EXAM_RESULT_NOT_FOUND: "O resultado do exame não foi encontrado.",
    ASSESSMENT_RESULT_IS_NOT_EXAM: "O resultado selecionado não corresponde a um exame.",
    SCHEDULE_TEACHER_CONFLICT: "Existe um conflito de horário para o professor.",
    TEACHER_ASSIGNMENT_CONTEXT_MISMATCH: "A atribuição do professor não corresponde ao contexto da turma.",
    COURSE_OFFERING_NOT_FOUND: "A disciplina da turma não foi encontrada.",
    ASSESSMENT_PERIOD_NOT_FOUND: "O período de avaliação não foi encontrado.",
    STUDENT_NOT_COURSE_PARTICIPANT: "O aluno não está inscrito nesta disciplina.",
    FINANCIAL_SCOPE_VIOLATION: "A operação financeira não corresponde ao ano letivo ou escola selecionados.",
    PAYMENT_ALLOCATION_EXCEEDS_PAYMENT: "O valor atribuído ultrapassa o valor do pagamento.",
    PAYMENT_ALLOCATION_EXCEEDS_CHARGE: "O valor atribuído ultrapassa o valor da obrigação.",
    RECEIPT_PAYMENT_NOT_CONFIRMED: "Só é possível emitir recibo para pagamentos confirmados.",
    PAYMENT_ALREADY_REVERSED: "Este pagamento já foi estornado.",
    SCHOOL_NOT_FOUND: "A escola selecionada não está disponível.",
    STUDENT_NOT_FOUND: "O aluno solicitado não foi encontrado.",
    STUDENT_SCHOOL_NUMBER_ALREADY_EXISTS: "O número do aluno já está atribuído a outro aluno.",
    NATIONAL_ID_ALREADY_EXISTS: "O documento de identificação já está associado a outro registo.",
    GUARDIAN_IDENTITY_NUMBER_ALREADY_EXISTS: "O documento do encarregado já está associado a outro registo.",
    ACTIVE_ENROLLMENT_ALREADY_EXISTS: "Já existe uma matrícula ativa para este aluno no período indicado.",
    ENROLLMENT_NOT_FOUND: "A matrícula solicitada não foi encontrada.",
    ENROLLMENT_NOT_PLACABLE: "Esta matrícula não pode ser colocada numa turma no estado atual.",
    CLASS_GROUP_NOT_FOUND: "A turma solicitada não foi encontrada.",
    CLASS_GROUP_NOT_OPEN: "A turma não está aberta para receber alunos.",
    CLASS_CONTEXT_MISMATCH: "A turma não corresponde à escola, ano ou classe da matrícula.",
    PLACEMENT_DATE_OUTSIDE_ACADEMIC_YEAR: "A colocação está fora das datas do ano letivo.",
    CLASS_CAPACITY_REACHED: "A capacidade da turma foi atingida.",
    GRADE_LEVEL_NOT_FOUND: "A classe selecionada não foi encontrada.",
    PATHWAY_NOT_FOUND: "O percurso/área selecionado não foi encontrado.",
    CLASS_GROUP_PATHWAY_CYCLE_MISMATCH: "O percurso selecionado não pertence ao ciclo da classe.",
    CLASS_GROUP_PATHWAY_SCHOOL_MISMATCH: "O percurso selecionado não pertence à escola da turma.",
    TEACHER_NOT_FOUND_IN_SCHOOL: "O professor não pertence à escola selecionada.",
    DIRECTOR_MUST_TEACH_CLASS: "O diretor de turma deve estar atribuído a uma disciplina dessa turma.",
    DIRECTOR_DATES_OUTSIDE_ACADEMIC_YEAR: "O período da direção de turma está fora do ano letivo.",
    COURSE_OFFERING_CLASS_CONTEXT_MISMATCH: "A oferta disciplinar não pertence ao contexto da turma.",
    SUBJECT_NOT_FOUND: "A disciplina selecionada não foi encontrada.",
    COURSE_OFFERING_SUBJECT_SCHOOL_MISMATCH: "A disciplina não pertence à escola da oferta.",
    CURRICULUM_SUBJECT_NOT_FOUND: "A disciplina não está configurada no currículo.",
    COURSE_OFFERING_CURRICULUM_CONTEXT_MISMATCH: "A oferta não corresponde ao currículo da classe.",
    COURSE_OFFERING_SUBJECT_MISMATCH: "A disciplina da oferta não corresponde à configuração curricular.",
    ACADEMIC_YEAR_NOT_FOUND: "O ano letivo não foi encontrado.",
    ACADEMIC_YEAR_NOT_EDITABLE: "O ano letivo não pode ser alterado no estado atual.",
    SECTION_CODE_REQUIRED: "Indique o código da secção da turma.",
    INVALID_CLASS_CAPACITY: "A capacidade indicada para a turma não é válida.",
    CLASS_GROUP_NOT_EDITABLE: "A turma não pode ser alterada no estado atual.",
    CLASS_PATHWAY_CHANGE_REQUIRES_EMPTY_CLASS: "O percurso da turma só pode ser alterado enquanto a turma estiver vazia.",
    CLASS_CLOSE_DATE_OUTSIDE_ACADEMIC_YEAR: "A data de fecho está fora do ano letivo.",
    CLASS_GROUP_ALREADY_CLOSED: "A turma já está fechada.",
    COURSE_OFFERING_NOT_ASSIGNABLE: "A oferta disciplinar não pode receber um professor no estado atual.",
    TEACHER_ASSIGNMENT_DATES_OUTSIDE_ACADEMIC_YEAR: "As datas da atribuição docente estão fora do ano letivo.",
    TEACHER_NOT_FOUND: "O professor não foi encontrado.",
    TEACHER_SCHOOL_MISMATCH: "O professor não pertence à escola da oferta.",
    TRANSFER_REASON_REQUIRED: "Indique o motivo da transferência de turma.",
    ENROLLMENT_NOT_TRANSFERABLE: "A matrícula não pode ser transferida no estado atual.",
    CURRENT_CLASS_PLACEMENT_NOT_FOUND: "A colocação atual do aluno não foi encontrada.",
    TARGET_CLASS_NOT_FOUND: "A turma de destino não foi encontrada.",
    TRANSFER_TARGET_CONTEXT_MISMATCH: "A turma de destino não corresponde ao contexto da matrícula.",
    TRANSFER_TARGET_IS_CURRENT_CLASS: "A turma de destino já é a turma atual.",
    TARGET_CLASS_NOT_OPEN: "A turma de destino não está aberta.",
    TRANSFER_DATE_OUTSIDE_ACADEMIC_YEAR: "A data da transferência está fora do ano letivo.",
    TRANSFER_DATE_MUST_FOLLOW_CURRENT_PLACEMENT: "A transferência deve ocorrer depois do início da colocação atual.",
    TARGET_CLASS_CAPACITY_REACHED: "A capacidade da turma de destino foi atingida.",
    UNKNOWN: "Não foi possível concluir a operação. Tente novamente ou contacte a administração.",
  };
  return messages[code];
}
