"use client";
import * as React from "react";
import {useRouter} from "next/navigation";
import {useTransition} from "react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {createTeacherAction} from "@/lib/sige/teacher-actions";
export function TeacherForm({schoolId}:{schoolId:string}){const router=useRouter();const[pending,start]=useTransition();const[v,setV]=React.useState({employeeCode:"",fullName:"",gender:"",birthDate:"",nationalId:"",phone:"",address:""});const set=(k:keyof typeof v,x:string)=>setV(s=>({...s,[k]:x}));function submit(e:React.FormEvent){e.preventDefault();start(async()=>{const r=await createTeacherAction({...v,schoolId});if(!r.ok){toast.error("Não foi possível criar o professor",{description:r.code});return}toast.success("Professor registado");router.push("/professores");router.refresh()})}return <form onSubmit={submit} className="space-y-6"><div className="grid gap-5 md:grid-cols-2"><div className="space-y-2"><Label>Código do professor</Label><Input required value={v.employeeCode} onChange={e=>set("employeeCode",e.target.value)} placeholder="PROF-001"/></div><div className="space-y-2"><Label>Nome completo</Label><Input required value={v.fullName} onChange={e=>set("fullName",e.target.value)}/></div><div className="space-y-2"><Label>Sexo</Label><Input value={v.gender} onChange={e=>set("gender",e.target.value)} placeholder="Opcional"/></div><div className="space-y-2"><Label>Data de nascimento</Label><Input type="date" value={v.birthDate} onChange={e=>set("birthDate",e.target.value)}/></div><div className="space-y-2"><Label>BI / documento</Label><Input value={v.nationalId} onChange={e=>set("nationalId",e.target.value)}/></div><div className="space-y-2"><Label>Telefone</Label><Input value={v.phone} onChange={e=>set("phone",e.target.value)}/></div><div className="space-y-2 md:col-span-2"><Label>Residência</Label><Input value={v.address} onChange={e=>set("address",e.target.value)}/></div></div><p className="text-sm text-muted-foreground">E-mail não é obrigatório. O cadastro do professor não depende de e-mail institucional.</p><Button disabled={pending}>{pending?"A guardar…":"Registar professor"}</Button></form>}